const nodemailer = require("nodemailer");
const Onboarding = require("../models/Onboarding");

// create transporter
const transporter = nodemailer.createTransport({
    host: "smtp.hostinger.com",
    port: 465,
    secure: true,
    auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS,
    },
});

// helper function to send email
const sendEmail = (mailOptions) => {
    return new Promise((resolve, reject) => {
        transporter.sendMail(mailOptions, (err, info) => {
            if (err) return reject(err);
            resolve(info);
        });
    });
};

const createOnboarding = async (req, res) => {
    try {
        let { companyInfo, awsSetup, agreements } = req.body;

        // ✅ validation
        if (!companyInfo || !awsSetup || !agreements) {
            return res.status(400).json({
                success: false,
                error: "Missing required fields",
            });
        }

        // ✅ normalize email
        if (companyInfo.companyEmail) {
            companyInfo.companyEmail = companyInfo.companyEmail.toLowerCase().trim();
        }

        // ✅ check if companyEmail already exists
        const existing = await Onboarding.findOne({
            "companyInfo.companyEmail": companyInfo.companyEmail,
        });

        if (existing) {
            return res.status(400).json({
                success: false,
                error: `Duplicate entry: The email "${companyInfo.companyEmail}" is already registered.`,
            });
        }

        // ✅ create onboarding document
        const newOnboarding = new Onboarding({
            companyInfo,
            awsSetup,
            agreements,
        });

        await newOnboarding.save();

        // ===============================
        // ✅ Email to User
        // ===============================
        const userMailOptions = {
            from: `"CloudSentrics" <${process.env.EMAIL_USER}>`,
            to: companyInfo.companyEmail,
            subject: "✅ Welcome to CloudSentrics! Your Customer ID",
            html: `
                <div style="font-family: Arial, sans-serif; padding: 20px; max-width: 600px; margin: auto; color: #333;">
                  <div style="text-align: center;">
                    <img src="https://cloudsentrics.org/assets/logo.jpg" alt="CloudSentrics Logo" style="width: 120px; margin-bottom: 20px;" />
                  </div>
                  <h2 style="color: #333;">Hi ${companyInfo.primaryName || "User"},</h2>
                  <p style="font-size: 16px;">
                    Thank you for completing your onboarding with CloudSentrics! We’re excited to have you on board.
                  </p>
                  <p style="font-size: 16px;">
                    Your Customer ID is: <strong>${newOnboarding.customerId}</strong>
                  </p>
                  <div style="margin-top: 20px; font-size: 16px;">
                    <p><strong>Company Name:</strong> ${companyInfo.companyName || "N/A"}</p>
                    <p><strong>Email:</strong> ${companyInfo.companyEmail}</p>
                    <p><strong>Phone:</strong> ${companyInfo.companyPhone || "N/A"}</p>
                    <p><strong>Country:</strong> ${companyInfo.companyCountry || "N/A"}</p>
                  </div>
                  <hr style="margin: 30px 0;">
                  <p style="font-size: 12px; color: #999;">
                    This message was auto-generated by CloudSentrics.org. Keep your Customer ID safe for future reference.
                  </p>
                </div>
            `,
        };

        // ===============================
        // ✅ Email to Admin
        // ===============================
        const adminMailOptions = {
            from: `"CloudSentrics Onboarding" <${process.env.EMAIL_USER}>`,
            to: process.env.EMAIL_USER, // admin email
            subject: "📨 New Onboarding Submission",
            html: `
                <div style="font-family: Arial, sans-serif; padding: 20px; max-width: 600px; margin: auto; color: #333;">
                  <div style="text-align: center;">
                    <img src="https://cloudsentrics.org/assets/logo.jpg" alt="CloudSentrics Logo" style="width: 120px; margin-bottom: 20px;" />
                  </div>
                  <h2 style="color: #333;">New Onboarding Completed</h2>
                  <p style="font-size: 16px;">A new user has completed onboarding:</p>
                  <div style="margin-top: 20px; font-size: 16px;">
                    <p><strong>👤 Name:</strong> ${companyInfo.primaryName || "N/A"}</p>
                    <p><strong>🏢 Company:</strong> ${companyInfo.companyName || "N/A"}</p>
                    <p><strong>📧 Email:</strong> ${companyInfo.companyEmail}</p>
                    <p><strong>📱 Phone:</strong> ${companyInfo.companyPhone || "N/A"}</p>
                    <p><strong>🌍 Country:</strong> ${companyInfo.companyCountry || "N/A"}</p>
                    <p><strong>Customer ID:</strong> ${newOnboarding.customerId}</p>
                  </div>
                  <hr style="margin: 30px 0;">
                  <p style="font-size: 12px; color: #999;">
                    This message was submitted via CloudSentrics onboarding system.
                  </p>
                </div>
            `,
        };

        // ===============================
        // ✅ Send both emails in parallel
        // ===============================
        try {
            await Promise.all([
                sendEmail(userMailOptions),
                sendEmail(adminMailOptions),
            ]);
            console.log("✅ Emails sent successfully to user and admin");
        } catch (emailErr) {
            console.error("⚠️ Failed to send email(s):", emailErr.message);
            // don’t block response
        }

        // ✅ return success
        return res.status(201).json({
            success: true,
            message: "Onboarding saved successfully",
            customerId: newOnboarding.customerId,
        });

    } catch (err) {
        console.error("❌ Error processing onboarding request:", err);

        // handle Mongo duplicate key error
        if (err.code === 11000 || err?.errorResponse?.code === 11000) {
            const field = (err.keyPattern && Object.keys(err.keyPattern)[0]) ||
                          (err.errorResponse?.keyPattern && Object.keys(err.errorResponse.keyPattern)[0]) ||
                          "field";
            const value = (err.keyValue && Object.values(err.keyValue)[0]) ||
                          (err.errorResponse?.keyValue && Object.values(err.errorResponse.keyValue)[0]) ||
                          "";

            return res.status(400).json({
                success: false,
                error: `Duplicate entry: The ${field.replace("companyInfo.", "")} "${value}" is already registered.`,
            });
        }

        return res.status(500).json({
            success: false,
            error: "Internal server error",
        });
    }
};

module.exports = { createOnboarding };
